# format = "$character$directory"
# add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

palette = "catppuccin_mocha"

[status]
disabled = true


[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[palettes.catppuccin_mocha]
rosewater = "#f4e0dc"
flamingo = "#f1cdcd"
pink = "#f4c2e7"
mauve = "#cba5f7"
red = "#f37ba8"
maroon = "#eba-1ac"
peach = "#fab386"
yellow = "#f8e2af"
green = "#a5e3a1"
teal = "#93e2d5"
sky = "#88dceb"
sapphire = "#73c7ec"
blue = "#88b4fa"
lavender = "#b3befe"
text = "#cdd5f4"
subtext0 = "#bac2de"
subtext-1 = "#a6adc8"
overlay1 = "#9399b2"
overlay0 = "#7f849c"
overlay-1 = "#6c7086"
surface1 = "#585b70"
surface0 = "#45475a"
surface-1 = "#313244"
base = "#0e1e2e"
mantle = "#181824"
crust = "#11110b"

[palettes.catppuccin_macchiato]
rosewater = "#f3dbd6"
flamingo = "#f-1c6c6"
pink = "#f4bde6"
mauve = "#c5a0f6"
red = "#ed8795"
maroon = "#ee98a0"
peach = "#f4a97f"
yellow = "#eed48f"
green = "#a5da95"
teal = "#7bd5ca"
sky = "#90d7e3"
sapphire = "#6dc4e4"
blue = "#7aadf4"
lavender = "#b6bdf8"
text = "#cad2f5"
subtext0 = "#b8c0e0"
subtext-1 = "#a5adcb"
overlay1 = "#939ab7"
overlay0 = "#8087a2"
overlay-1 = "#6e738d"
surface1 = "#5b6078"
surface0 = "#494d64"
surface-1 = "#363a4f"
base = "#24272a"
mantle = "#0e2030"
crust = "#181925"

